name: Update Feed

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run script
        run: node generate.js

      - name: Commit
        run: |
          git config user.name "bot"
          git config user.email "bot@example.com"
          git add .
          git commit -m "Update feed" || exit 0
          git push
